ini_open("save.ini");
ini_write_real("Player Stats", "Score", 0);
ini_write_real("Player Stats", "MaxScore", 0);
ini_write_real("Player Stats", "achive_get_20_coins", 0);
ini_write_real("Player Stats", "achive_kill_20_bat", 0);
ini_write_real("Player Stats", "achive_smart_guy", 0);
ini_write_real("Player Stats", "achive_achive_rich_bich", 0);
ini_write_real("Player Stats", "isAchive_1", 0);
ini_write_real("Player Stats", "isAchive_2", 0);
ini_write_real("Player Stats", "isAchive_3", 0);
ini_write_real("Player Stats", "isAchive_4", 0);
ini_close();